backend:
  name: git-gateway
  repo: crosby-solutions-content
  branch: master # Branch to update (optional; defaults to master)

# CMS customisation setup
site_url: https://crosby.solutions # for previews
display_url: https://crosby.solutions # for linking back to the site
logo_url: https://crosby.solutions/images/logo.svg # TODO find a static link to an image

# uses pull requests to set up a draft mode kanban style board for drafts, review and publish
publish_mode: editorial_workflow

# where should content go
media_folder: 'images/uploads' # Media files will be stored in the repo under images/uploads
# check that this isn't going to mess up with content being a submodule?
# media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'articles' # Used in routes, e.g., /admin/collections/blog
    label: 'Articles' # Used in the UI
    folder: 'content/articles' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'logo', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'proposals' # Used in routes, e.g., /admin/collections/blog
    label: 'Proposals' # Used in the UI
    folder: 'content/clients' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'logo', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'json' # Used in routes, e.g., /admin/collections/blog
    label: 'JSON' # Used in the UI
    extension: 'json'
    editor-preview: 'false'
    files: 
    - file: 'content/json/about.json' # The path to the folder where the documents are stored
      label: 'About'
      name: 'about'
      fields:
      - { title: body, para: body, widget: code }
  - file: 'content/json/clients.json' # The path to the folder where the documents are stored
      label: 'Clients'
      name: 'clients'
      fields:
      - { name: body, img: body, link: body, widget: code }
  - file: 'content/json/features.json' # The path to the folder where the documents are stored
      label: 'Features'
      name: 'features'
      fields:
      - { title: body, content: body, hex-text: code }
  - file: 'content/json/for-you-options.json' # The path to the folder where the documents are stored
      label: 'For You Options'
      name: 'for-you-options'
      fields:
      - { title: body, list: body, content: body, widget: code }
  - file: 'content/json/social.json' # The path to the folder where the documents are stored
      label: 'Social'
      name: 'social'
      fields:
      - { href: body, name: body, avatar: body, banner: body, content: body, widget: code }
  - file: 'content/json/solutions.json' # The path to the folder where the documents are stored
      label: 'Solutions'
      name: 'solutions'
      fields:
      - { title: body, para: body, widget: code }
  - file: 'content/json/tech.json' # The path to the folder where the documents are stored
      label: 'Tech'
      name: 'tech'
      fields:
      - { title: body, content: body, widget: code }
